begin;

-- Ensure source categories exist for incoming product rows
insert into public.product_categories (
  id,
  name,
  slug,
  label,
  description,
  image,
  subcategories,
  example_products,
  product_count
)
values
('herbal-extracts', 'Herbal Extracts', 'herbal-extracts', 'Premium Extracts', 'High-potency standardized extracts from premium botanicals, manufactured under strict GMP conditions to ensure consistent active compound levels.', '/images/Product%20Card%20Backgrounds.png', array['Root Extracts', 'Leaf Extracts', 'Bark Extracts', 'Fruit Extracts', 'Flower Extracts'], array['Curcumin 95%', 'Ashwagandha Root', 'Green Tea Extract'], 0),
('essential-oils', 'Essential Oils', 'essential-oils', 'Therapeutic Grade', 'Pure, therapeutic-grade essential oils sourced from the finest botanicals across India. Steam distilled and cold-pressed for maximum potency.', '/images/Product%20Card%20Backgrounds.png', array['Floral Oils', 'Herbal Oils', 'Spice Oils', 'Wood Oils', 'Citrus Oils'], array['Clove Leaf Oil', 'Eucalyptus Oil', 'Peppermint Oil'], 0),
('oleoresins', 'Oleoresins', 'oleoresins', 'High Potency', 'Concentrated oleoresins capturing the complete flavor and bioactive profile of spices and herbs through advanced solvent extraction.', '/images/Product%20Card%20Backgrounds.png', array['Spice Oleoresins', 'Herb Oleoresins', 'Capsicum Oleoresins'], array['Turmeric Oleoresin', 'Paprika Oleoresin', 'Black Pepper Oleoresin'], 0),
('fruit-juice-powders', 'Fruit Juice Powders', 'fruit-juice-powders', 'Natural Concentrates', 'Spray-dried fruit juice powders retaining the natural color, flavor, and nutritional profile of fresh fruits. Ideal for food & beverage applications.', '/images/Product%20Card%20Backgrounds.png', array['Tropical Fruit Powders', 'Berry Powders', 'Citrus Powders'], array['Amla Powder', 'Pomegranate Powder', 'Mango Powder'], 0),
('phytochemicals', 'Phytochemicals', 'phytochemicals', 'Research Grade', 'High-purity phytochemical isolates for pharmaceutical, nutraceutical, and research applications. HPLC-verified for potency and purity.', '/images/Product%20Card%20Backgrounds.png', array['Flavonoids', 'Alkaloids', 'Polyphenols', 'Terpenoids', 'Glycosides'], array['Curcuminoids', 'Piperine 95%', 'Quercetin'], 0),
('amino-acids', 'Amino Acids', 'amino-acids', 'Essential Nutrients', 'Pharmaceutical and food-grade amino acids manufactured to the highest purity standards. Available in both L-form and DL-form configurations.', '/images/Product%20Card%20Backgrounds.png', array['Essential Amino Acids', 'Non-Essential Amino Acids', 'Branched-Chain Amino Acids'], array['L-Glutamine', 'L-Arginine', 'L-Lysine'], 0),
('nutraceuticals', 'Nutraceuticals', 'nutraceuticals', 'Health & Wellness', 'Comprehensive range of nutraceutical ingredients for dietary supplements, functional foods, and wellness products. Backed by clinical research.', '/images/Product%20Card%20Backgrounds.png', array['Vitamins & Minerals', 'Probiotics', 'Omega Fatty Acids', 'Plant Proteins', 'Dietary Fibers'], array['Omega-3 Fish Oil', 'Collagen Peptides', 'Glucosamine'], 0)
on conflict (id) do update set
  name = excluded.name,
  slug = excluded.slug,
  label = excluded.label,
  description = excluded.description,
  image = excluded.image,
  subcategories = excluded.subcategories,
  example_products = excluded.example_products;

insert into public.products (
  id,
  name,
  slug,
  category_id,
  botanical_name,
  active_ingredient,
  active_compound,
  concentration,
  applications,
  description,
  image_path,
  quality_badges,
  is_halal,
  popularity
)
values
('acai-berry-extract', 'Acai Berry Extract', 'acai-berry-extract', 'herbal-extracts', 'Euterpe oleracea', 'Polyphenols 10%–20%', null, null, array['Antioxidant Support', 'Skin Health', 'Anti-Aging'], null, null, array[]::text[], null, null),
('acerola-cherry-extract', 'Acerola Cherry Extract', 'acerola-cherry-extract', 'herbal-extracts', 'Malpighia glabra', 'Natural Vitamin C 17%–25%', null, null, array['Immunity Boost', 'Skin Health', 'Antioxidant Support'], null, null, array[]::text[], null, null),
('aloe-vera-extract', 'Aloe Vera Extract', 'aloe-vera-extract', 'herbal-extracts', 'Aloe barbadensis', 'Polyphenols / 200:1', null, null, array['Cosmetics'], null, null, array[]::text[], null, null),
('amaltas-extract', 'Amaltas Extract', 'amaltas-extract', 'herbal-extracts', 'Cassia fistula', 'Anthraquinones 5%', null, null, array['Natural Laxative', 'Detox Support', 'Skin Health'], null, null, array[]::text[], null, null),
('amla-extract', 'Amla Extract', 'amla-extract', 'herbal-extracts', 'Emblica officinalis', 'Tannins 20%–50%', null, null, array['Skin & Hair Care', 'Anti-Aging'], null, null, array[]::text[], null, null),
('anar-chilka-extract', 'Anar Chilka Extract', 'anar-chilka-extract', 'herbal-extracts', 'Punica granatum (Peel)', 'Ellagic Acid 20%–40%', null, null, array['Antioxidant', 'Gut Health', 'Oral & Skin Care Support'], null, null, array[]::text[], null, null),
('apamarga-extract', 'Apamarga Extract', 'apamarga-extract', 'herbal-extracts', 'Achyranthes aspera', 'Saponins 10%', null, null, array['Diuretic Support', 'Digestive Health', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('apple-extract', 'Apple Extract', 'apple-extract', 'herbal-extracts', 'Malus domestica', 'Polyphenols 40%', null, null, array['Antioxidant', 'Skin Health', 'Cardiovascular Support'], null, null, array[]::text[], null, null),
('arjuna-extract', 'Arjuna Extract', 'arjuna-extract', 'herbal-extracts', 'Terminalia arjuna', 'Arjunolic Acid, 0.1% Tannins', null, null, array['Cardiac Health'], null, 'terminalia-arjuna-extract.jpg', array[]::text[], null, null),
('artichoke-extract', 'Artichoke Extract', 'artichoke-extract', 'herbal-extracts', 'Cynara scolymus', 'Cynarin 2.5%', null, null, array['Liver Health', 'Digestive Support', 'Cholesterol Management'], null, null, array[]::text[], null, null),
('ashoka-chaal-extract', 'Ashoka Chaal Extract', 'ashoka-chaal-extract', 'herbal-extracts', 'Saraca asoca', 'Tannins 10%–20%', null, null, array['Female Reproductive Health', 'Uterine Tonic', 'Menstrual Support'], null, null, array[]::text[], null, null),
('astragalus-extract', 'Astragalus Extract', 'astragalus-extract', 'herbal-extracts', 'Astragalus membranaceus', 'Polysaccharides 50%', null, null, array['Immune Support', 'Anti-aging', 'Adaptogen'], null, null, array[]::text[], null, null),
('ashwagandha-extract', 'Ashwagandha Extract', 'ashwagandha-extract', 'herbal-extracts', 'Withania somnifera', 'Withanolides 1.5%–10%', null, null, array['Stress Relief', 'Adaptogen'], null, 'ashwagandha-extract.jpg', array[]::text[], null, null),
('bacopa-extract', 'Bacopa Extract', 'bacopa-extract', 'herbal-extracts', 'Bacopa monnieri', 'Bacosides 20%–50% USP', null, null, array['Memory Support'], null, 'bacopa-extract.jpg', array[]::text[], null, null),
('baheda-extract', 'Baheda Extract', 'baheda-extract', 'herbal-extracts', 'Terminalia bellirica', 'Tannins 30%', null, null, array['Digestive Harmony'], null, null, array[]::text[], null, null),
('banaba-extract', 'Banaba Extract', 'banaba-extract', 'herbal-extracts', 'Lagerstroemia speciosa', 'Corosolic Acid 1%–2%', null, null, array['Blood Sugar', 'Weight'], null, null, array[]::text[], null, null),
('beet-root-extract', 'Beet Root Extract', 'beet-root-extract', 'herbal-extracts', 'Beta vulgaris', 'Betanin, Nitrates', null, null, array['Sports Nutrition', 'Heart Health'], null, null, array[]::text[], null, null),
('berberine-extract', 'Berberine Extract', 'berberine-extract', 'herbal-extracts', 'Berberis aristata', 'Berberine 97% (HPLC)', null, null, array['Blood Sugar Support', 'Gut Health', 'Anti-microbial'], null, null, array[]::text[], null, null),
('beta-carotene-extract', 'Beta Carotene Extract', 'beta-carotene-extract', 'herbal-extracts', 'Daucus carota', 'Beta Carotene 30%', null, null, array['Skin Health', 'Antioxidant'], null, null, array[]::text[], null, null),
('bhringraj-extract', 'Bhringraj Extract', 'bhringraj-extract', 'herbal-extracts', 'Eclipta alba', 'Bitters 6%', null, null, array['Liver Support'], null, null, array[]::text[], null, null),
('bhumi-amla-extract', 'Bhumi Amla Extract', 'bhumi-amla-extract', 'herbal-extracts', 'Phyllanthus niruri', 'Bitters 5%', null, null, array['Liver', 'Kidney', 'Diabetes'], null, null, array[]::text[], null, null),
('bidarikand-extract', 'Bidarikand Extract', 'bidarikand-extract', 'herbal-extracts', 'Pueraria tuberosa', 'Saponins 20%', null, null, array['Male Vitality', 'Rejuvenation', 'Muscle Strength Support'], null, null, array[]::text[], null, null),
('bilberry-extract', 'Bilberry Extract', 'bilberry-extract', 'herbal-extracts', 'Vaccinium myrtillus', 'Anthocyanins 25% (UV)', null, null, array['Eye Health', 'Antioxidant', 'Vision Support'], null, null, array[]::text[], null, null),
('bitter-melon-extract', 'Bitter Melon Extract', 'bitter-melon-extract', 'herbal-extracts', 'Momordica charantia', 'Charantin 0.5%, Bitters 10% & 20%', null, null, array['Blood Sugar'], null, null, array[]::text[], null, null),
('black-cohosh-extract', 'Black Cohosh Extract', 'black-cohosh-extract', 'herbal-extracts', 'Cimicifuga racemosa', 'Triterpene Glycosides 2.5%', null, null, array['Menopause Support', 'Hormonal Balance', 'Women''s Health'], null, null, array[]::text[], null, null),
('black-currant-extract', 'Black Currant Extract', 'black-currant-extract', 'herbal-extracts', 'Ribes nigrum', 'Anthocyanins 25% (UV)', null, null, array['Vision Support', 'Immunity Boost', 'Antioxidant'], null, null, array[]::text[], null, null),
('black-pepper-extract', 'Black Pepper Extract', 'black-pepper-extract', 'herbal-extracts', 'Piper nigrum', 'Piperine 95%', null, null, array['Bioavailability', 'Respiratory'], null, 'black-pepper.jpg', array[]::text[], null, null),
('blueberry-extract', 'Blueberry Extract', 'blueberry-extract', 'herbal-extracts', 'Vaccinium corymbosum', 'Anthocyanins 25% (UV)', null, null, array['Eye Health', 'Cognitive Support', 'Antioxidant'], null, null, array[]::text[], null, null),
('boswellia-extract', 'Boswellia Extract', 'boswellia-extract', 'herbal-extracts', 'Boswellia serrata', 'Boswellic Acid 65-80%, AKBA 10-90%', null, null, array['Joints', 'Skin', 'Anti-inflammatory'], null, 'boswellia-extract.jpg', array[]::text[], null, null),
('burdock-seed-extract', 'Burdock Seed Extract', 'burdock-seed-extract', 'herbal-extracts', 'Arctium lappa (Seeds)', 'Inulin 10%', null, null, array['Detoxification', 'Liver Support', 'Skin & Blood Purifier'], null, null, array[]::text[], null, null),
('butterbur-nut-extract', 'Butterbur Nut Extract', 'butterbur-nut-extract', 'herbal-extracts', 'Petasites hybridus', 'Petasin & Isopetasin 15%', null, null, array['Migraine Support', 'Allergy Relief', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('capsicum-extract', 'Capsicum Extract', 'capsicum-extract', 'herbal-extracts', 'Capsicum annum', 'Capsaicin 80%–90%', null, null, array['Pain', 'Inflammation'], null, null, array[]::text[], null, null),
('caralluma-extract', 'Caralluma Extract', 'caralluma-extract', 'herbal-extracts', 'Caralluma fimbriata', 'Glycosides 20%', null, null, array['Weight Management'], null, null, array[]::text[], null, null),
('cat-s-claw-extract', 'Cat''s Claw Extract', 'cat-s-claw-extract', 'herbal-extracts', 'Uncaria tomentosa', 'Alkaloids 3%–5%', null, null, array['Immune Modulation', 'Joint Support', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('chaste-berry-extract', 'Chaste Berry Extract', 'chaste-berry-extract', 'herbal-extracts', 'Vitex agnus-castus', 'Agnusides 0.5%–1%', null, null, array['PMS Relief', 'Hormonal Balance', 'Female Reproductive Support'], null, null, array[]::text[], null, null),
('chireta-extract', 'Chireta Extract', 'chireta-extract', 'herbal-extracts', 'Swertia chirata', 'Bitters 10%–20%', null, null, array['Liver Support', 'Blood Purifier', 'Antimicrobial Activity'], null, null, array[]::text[], null, null),
('chitrakmool-extract', 'Chitrakmool Extract', 'chitrakmool-extract', 'herbal-extracts', 'Plumbago zeylanica', 'Plumbagin 2%–5%', null, null, array['Digestive Stimulant', 'Metabolism Support', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('chlorela-powder', 'Chlorela Powder', 'chlorela-powder', 'herbal-extracts', 'Chlorella vulgaris', 'Natural Chlorophyll 60%', null, null, array['Detoxification', 'Alkalizing', 'Immune Support'], null, null, array[]::text[], null, null),
('cinnamon-extract', 'Cinnamon Extract', 'cinnamon-extract', 'herbal-extracts', 'Cinnamomum cassia', 'Polyphenols 10%–20%', null, null, array['Antioxidant', 'Anti-diabetic'], null, 'cinnamon-extract.jpg', array[]::text[], null, null),
('citrus-aurantium-extract', 'Citrus Aurantium Extract', 'citrus-aurantium-extract', 'herbal-extracts', 'Citrus aurantium', 'Synephrine 6%–10%', null, null, array['Weight Management', 'Thermogenic', 'Appetite Control'], null, null, array[]::text[], null, null),
('coleus-extract', 'Coleus Extract', 'coleus-extract', 'herbal-extracts', 'Coleus forskohlii', 'Forskolin 10%–20%', null, null, array['Weight', 'Sports Health'], null, 'coleus-extract.jpg', array[]::text[], null, null),
('cranberry-extract', 'Cranberry Extract', 'cranberry-extract', 'herbal-extracts', 'Vaccinium macrocarpon', 'Proanthocyanidins 25%', null, null, array['Urinary Tract Health', 'Antioxidant', 'Women''s Wellness'], null, null, array[]::text[], null, null),
('damiana-extract', 'Damiana Extract', 'damiana-extract', 'herbal-extracts', 'Turnera diffusa', 'Flavonoids 5%', null, null, array['Libido Enhancement', 'Mood Support', 'Nervine Tonic'], null, null, array[]::text[], null, null),
('dandelion-leaf-extract', 'Dandelion Leaf Extract', 'dandelion-leaf-extract', 'herbal-extracts', 'Taraxacum officinale', 'Taraxacin 4%', null, null, array['Liver Support', 'Diuretic', 'Detoxification'], null, null, array[]::text[], null, null),
('devil-s-claw-extract', 'Devil''s Claw Extract', 'devil-s-claw-extract', 'herbal-extracts', 'Harpagophytum procumbens', 'Harpagosides 1.5%–5%', null, null, array['Joint Support', 'Anti-inflammatory', 'Pain Relief'], null, null, array[]::text[], null, null),
('fenugreek-extract', 'Fenugreek Extract', 'fenugreek-extract', 'herbal-extracts', 'Trigonella foenumgraecum', 'Saponins 40%–50%', null, null, array['Glucose & Heart Health'], null, 'fenugreek-extract.jpg', array[]::text[], null, null),
('feverfew-extract', 'Feverfew Extract', 'feverfew-extract', 'herbal-extracts', 'Tanacetum parthenium', 'Parthenolide 0.5%–1%', null, null, array['Migraine Support', 'Anti-inflammatory', 'Headache Relief'], null, null, array[]::text[], null, null),
('ganoderma-extract', 'Ganoderma Extract', 'ganoderma-extract', 'herbal-extracts', 'Ganoderma lucidum', 'Polysaccharides 30%–50%', null, null, array['Immunity Boost', 'Anti-stress', 'Liver & Heart Support'], null, null, array[]::text[], null, null),
('garcinia-cambogia-extract', 'Garcinia Cambogia Extract', 'garcinia-cambogia-extract', 'herbal-extracts', 'Garcinia cambogia', 'HCA 50%–60%', null, null, array['Appetite', 'Weight'], null, 'garcinia-cambogia-extract-powder.png', array[]::text[], null, null),
('garlic-extract', 'Garlic Extract', 'garlic-extract', 'herbal-extracts', 'Allium sativum', 'Allicin 0.5%–1%', null, null, array['Cardiovascular Support', 'Immunity Boost', 'Antimicrobial'], null, null, array[]::text[], null, null),
('ginger-extract', 'Ginger Extract', 'ginger-extract', 'herbal-extracts', 'Zingiber officinale', 'Gingerol 5%', null, null, array['Digestion', 'Inflammation'], null, 'ginger-extract.jpg', array[]::text[], null, null),
('gingko-biloba-extract', 'Gingko Biloba Extract', 'gingko-biloba-extract', 'herbal-extracts', 'Ginkgo biloba', 'Flavone Glycosides 24%, Terpene Lactones 6%', null, null, array['Cognitive Support', 'Memory Enhancement', 'Circulatory Health'], null, null, array[]::text[], null, null),
('gokhru-extract', 'Gokhru Extract', 'gokhru-extract', 'herbal-extracts', 'Tribulus terrestris', 'Saponins 55%', null, null, array['Sexual Wellness'], null, null, array[]::text[], null, null),
('gotu-kola-extract', 'Gotu Kola Extract', 'gotu-kola-extract', 'herbal-extracts', 'Centella asiatica', 'Asiaticosides 10–90%', null, null, array['Skin', 'Hair', 'Brain Health'], null, null, array[]::text[], null, null),
('grape-seed-extract-draksha', 'Grape Seed Extract (Draksha)', 'grape-seed-extract-draksha', 'herbal-extracts', 'Vitis vinifera', 'Proanthocyanidins 95% (OPC)', null, null, array['Antioxidant', 'Cardiovascular Support', 'Skin Health'], null, null, array[]::text[], null, null),
('green-coffee-extract', 'Green Coffee Extract', 'green-coffee-extract', 'herbal-extracts', 'Coffea robusta', 'Chlorogenic Acid 45%–50%', null, null, array['Antioxidant', 'Weight'], null, 'green-coffee-extract.jpg', array[]::text[], null, null),
('green-tea-extract', 'Green Tea Extract', 'green-tea-extract', 'herbal-extracts', 'Camellia sinensis', 'Polyphenols 98%, EGCG 40%', null, null, array['Antioxidant', 'Metabolism'], null, 'green-tea-extract.jpg', array[]::text[], null, null),
('guduchi-extract', 'Guduchi Extract', 'guduchi-extract', 'herbal-extracts', 'Tinospora cordifolia', 'Bitters 10%–20%', null, null, array['Immunity Booster', 'Antipyretic', 'Adaptogen', 'Detox Support'], null, null, array[]::text[], null, null),
('guggul-extract', 'Guggul Extract', 'guggul-extract', 'herbal-extracts', 'Commiphora mukul', 'Guggulsterones 2.5% E & Z by HPLC', null, null, array['Cholesterol', 'Fat Loss'], null, 'guggul-extract.jpg', array[]::text[], null, null),
('gymnema-extract', 'Gymnema Extract', 'gymnema-extract', 'herbal-extracts', 'Gymnema sylvestre', 'Gymnemic Acid 25%–75%', null, null, array['Sugar Blocker'], null, 'gymnema-extract.jpg', array[]::text[], null, null),
('hadjod-extract', 'Hadjod Extract', 'hadjod-extract', 'herbal-extracts', 'Cissus quadrangularis', 'Keto Sterones', null, null, array['Bone Repair'], null, null, array[]::text[], null, null),
('harad-extract', 'Harad Extract', 'harad-extract', 'herbal-extracts', 'Terminalia chebula', 'Tannins 50%', null, null, array['Digestive Health'], null, null, array[]::text[], null, null),
('holy-basil-extract', 'Holy Basil Extract', 'holy-basil-extract', 'herbal-extracts', 'Ocimum sanctum', 'Ursolic Acid 2.5%', null, null, array['Cough', 'Cold', 'Antioxidant'], null, null, array[]::text[], null, null),
('horny-goat-weed-extract', 'Horny Goat Weed Extract', 'horny-goat-weed-extract', 'herbal-extracts', 'Epimedium grandiflorum', 'Icariin 10%–20%', null, null, array['Male Vitality', 'Libido Enhancement', 'Bone & Joint Support'], null, null, array[]::text[], null, null),
('horse-chestnut-extract', 'Horse Chestnut Extract', 'horse-chestnut-extract', 'herbal-extracts', 'Aesculus hippocastanum', 'Aescin upto 90%', null, null, array['Varicose Veins', 'Circulation Support', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('jamun-extract', 'Jamun Extract', 'jamun-extract', 'herbal-extracts', 'Syzygium cumini (syn. Eugenia jambolana)', 'Jamboline 5%, Tannins 10%', null, null, array['Blood Sugar Support', 'Antioxidant', 'Digestive Health'], null, null, array[]::text[], null, null),
('jatamansi-extract', 'Jatamansi Extract', 'jatamansi-extract', 'herbal-extracts', 'Nardostachys jatamansi', 'Jatamansone 0.2%–0.5%', null, null, array['Stress Relief', 'Cognitive Support', 'Nervine Tonic', 'Sleep Aid'], null, null, array[]::text[], null, null),
('jivanti-extract', 'Jivanti Extract', 'jivanti-extract', 'herbal-extracts', 'Leptadenia reticulata', 'Alkaloids 0.5%–1%', null, null, array['Rejuvenation', 'Lactation Support', 'Immunity', 'Eye Health'], null, null, array[]::text[], null, null),
('kachnar-extract', 'Kachnar Extract', 'kachnar-extract', 'herbal-extracts', 'Bauhinia variegata', 'Tannins 10%–15%', null, null, array['Thyroid Support', 'Anti-inflammatory', 'Lymphatic Detox'], null, null, array[]::text[], null, null),
('kali-musli-extract', 'Kali Musli Extract', 'kali-musli-extract', 'herbal-extracts', 'Curculigo orchioides', 'Saponins 10%–20%', null, null, array['Male Vitality', 'Aphrodisiac', 'Strength & Rejuvenation'], null, null, array[]::text[], null, null),
('kalmegh-extract', 'Kalmegh Extract', 'kalmegh-extract', 'herbal-extracts', 'Andrographis paniculata', 'Andrographolides 10%–95%', null, null, array['Liver Tonic', 'Blood Cleanser'], null, null, array[]::text[], null, null),
('kalonji-extract', 'Kalonji Extract', 'kalonji-extract', 'herbal-extracts', 'Nigella sativa', 'Thymoquinone 5%', null, null, array['Antioxidant', 'Immune Support', 'Metabolism & Respiratory Health'], null, null, array[]::text[], null, null),
('kasni-extract', 'Kasni Extract', 'kasni-extract', 'herbal-extracts', 'Cichorium intybus', 'Inulin 10%', null, null, array['Liver Support', 'Digestive Health', 'Blood Purification'], null, null, array[]::text[], null, null),
('kasondi-extract', 'Kasondi Extract', 'kasondi-extract', 'herbal-extracts', 'Cassia occidentalis', 'Anthraquinones 5%', null, null, array['Liver Support', 'Skin Disorders', 'Blood Purifier', 'Laxative'], null, null, array[]::text[], null, null),
('khadir-extract', 'Khadir Extract', 'khadir-extract', 'herbal-extracts', 'Acacia catechu', 'Catechins 10%–20%', null, null, array['Oral Health', 'Skin Disorders', 'Blood Purification', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('kulthi-dal-extract', 'Kulthi Dal Extract', 'kulthi-dal-extract', 'herbal-extracts', 'Macrotyloma uniflorum', 'Flavonoids 5%–10%', null, null, array['Kidney Stone Management', 'Diuretic Support', 'Detoxification'], null, null, array[]::text[], null, null),
('kutki-extract', 'Kutki Extract', 'kutki-extract', 'herbal-extracts', 'Picrorhiza kurroa', 'Kutkin 4%–6%', null, null, array['Liver Support', 'Hepatoprotective', 'Digestive & Immune Health'], null, null, array[]::text[], null, null),
('liquorice-extract', 'Liquorice Extract', 'liquorice-extract', 'herbal-extracts', 'Glycyrrhiza glabra', 'Glycyrrhizic Acid 10%–20%', null, null, array['Digestion', 'Respiratory'], null, null, array[]::text[], null, null),
('lodhra-extract', 'Lodhra Extract', 'lodhra-extract', 'herbal-extracts', 'Symplocos racemosa', 'Tannins 10%–20%', null, null, array['Women''s Health', 'Uterine Tonic', 'Anti-inflammatory', 'Skin Health'], null, null, array[]::text[], null, null),
('macca-root-extract', 'Macca Root Extract', 'macca-root-extract', 'herbal-extracts', 'Lepidium meyenii', 'Macamides & Macaenes 0.5%–1%', null, null, array['Energy & Stamina', 'Hormonal Balance', 'Fertility & Libido Support'], null, null, array[]::text[], null, null),
('makoi-extract', 'Makoi Extract', 'makoi-extract', 'herbal-extracts', 'Solanum nigrum', 'Alkaloids 0.3%–0.5%', null, null, array['Liver Support', 'Anti-inflammatory', 'Gastric Protection', 'Detox'], null, null, array[]::text[], null, null),
('mango-amra-extract', 'Mango (Amra) Extract', 'mango-amra-extract', 'herbal-extracts', 'Mangifera indica', 'Mangiferin 10%–20%', null, null, array['Antioxidant', 'Skin Health', 'Immune Support', 'Digestive Wellness'], null, null, array[]::text[], null, null),
('manjistha-extract', 'Manjistha Extract', 'manjistha-extract', 'herbal-extracts', 'Rubia cordifolia', 'Rubiadin 1%–2%', null, null, array['Blood Purifier', 'Skin Health', 'Lymphatic Detox', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('marigold-extract', 'Marigold Extract', 'marigold-extract', 'herbal-extracts', 'Tagetes erecta', 'Lutein 5–20%, Zeaxanthin up to 4%', null, null, array['Eye Health'], null, null, array[]::text[], null, null),
('milk-thistle-extract', 'Milk Thistle Extract', 'milk-thistle-extract', 'herbal-extracts', 'Silybum marianum', 'Silymarin 80%', null, null, array['Liver Protection', 'Detox Support', 'Antioxidant', 'Hepatoprotective'], null, null, array[]::text[], null, null),
('moringa-extract', 'Moringa Extract', 'moringa-extract', 'herbal-extracts', 'Moringa oleifera', 'Total Saponins 10% / Polyphenols 20%', null, null, array['Nutritional Support', 'Antioxidant', 'Anti-inflammatory', 'Immune Boost'], null, 'moringa-extract.jpg', array[]::text[], null, null),
('mucuna-extract', 'Mucuna Extract', 'mucuna-extract', 'herbal-extracts', 'Mucuna pruriens', 'L-DOPA up to 50%', null, null, array['Libido', 'Mood Support'], null, null, array[]::text[], null, null),
('nagarmotha-extract', 'Nagarmotha Extract', 'nagarmotha-extract', 'herbal-extracts', 'Cyperus rotundus', 'Volatile Oils 1%–2%', null, null, array['Digestive Health', 'Weight Management', 'Anti-inflammatory', 'Skin Support'], null, null, array[]::text[], null, null),
('nagkesar-extract', 'Nagkesar Extract', 'nagkesar-extract', 'herbal-extracts', 'Mesua ferrea', 'Flavonoids 5%–10%', null, null, array['Bleeding Disorders', 'Skin Health', 'Anti-inflammatory', 'Uterine Tonic'], null, null, array[]::text[], null, null),
('neem-extract', 'Neem Extract', 'neem-extract', 'herbal-extracts', 'Azadirachta indica', 'Bitters up to 8%', null, null, array['Anti-bacterial', 'Skin'], null, 'neem-extract.jpg', array[]::text[], null, null),
('noni-extract-noni-fruit-powder', 'Noni Extract / Noni Fruit Powder', 'noni-extract-noni-fruit-powder', 'herbal-extracts', 'Morinda citrifolia', 'Polysaccharides 10%', null, null, array['Immunity Boost', 'Antioxidant', 'Digestive Support', 'Cellular Health'], null, null, array[]::text[], null, null),
('nirgundi-extract', 'Nirgundi Extract', 'nirgundi-extract', 'herbal-extracts', 'Vitex negundo', 'Flavonoids 5%–10%', null, null, array['Joint Support', 'Pain Relief', 'Anti-inflammatory', 'Respiratory Health'], null, null, array[]::text[], null, null),
('olive-leaf-extract', 'Olive Leaf Extract', 'olive-leaf-extract', 'herbal-extracts', 'Olea europaea', 'Oleuropein 20%', null, null, array['Heart Health', 'Antioxidant', 'Immune Support', 'Antimicrobial'], null, null, array[]::text[], null, null),
('pashanbheda-extract', 'Pashanbheda Extract', 'pashanbheda-extract', 'herbal-extracts', 'Bergenia ligulata', 'Bergenin 2%–4%', null, null, array['Kidney Stone Management', 'Diuretic Support', 'Urinary Tract Health'], null, null, array[]::text[], null, null),
('pippali-extract', 'Pippali Extract', 'pippali-extract', 'herbal-extracts', 'Piper longum', 'Piperine 5%–10%', null, null, array['Respiratory Health', 'Digestive Support', 'Bioavailability Enhancer', 'Immunity'], null, null, array[]::text[], null, null),
('punarnava-extract', 'Punarnava Extract', 'punarnava-extract', 'herbal-extracts', 'Boerhavia diffusa', 'Boeravinone 2%–4%', null, null, array['Diuretic Support', 'Kidney & Liver Health', 'Anti-inflammatory', 'Edema Management'], null, null, array[]::text[], null, null),
('pit-papara-extract', 'Pit Papara Extract', 'pit-papara-extract', 'herbal-extracts', 'Fumaria parviflora', 'Alkaloids 0.5%–1%', null, null, array['Liver Support', 'Skin Disorders', 'Digestive Cleanse', 'Blood Purifier'], null, null, array[]::text[], null, null),
('rhodiola-rosea-extract', 'Rhodiola rosea Extract', 'rhodiola-rosea-extract', 'herbal-extracts', 'Rhodiola rosea', 'Rosavins 3%, Salidroside 1%', null, null, array['Stress Reduction', 'Mental Performance', 'Energy', 'Adaptogen'], null, null, array[]::text[], null, null),
('rhubarb-extract', 'Rhubarb Extract', 'rhubarb-extract', 'herbal-extracts', 'Rheum emodi / Rheum officinale', 'Anthraquinones 5%–10%', null, null, array['Natural Laxative', 'Digestive Cleanse', 'Liver Support', 'Colon Health'], null, null, array[]::text[], null, null),
('rohitaka-extract', 'Rohitaka Extract', 'rohitaka-extract', 'herbal-extracts', 'Tecomella undulata', 'Flavonoids 5%–10%', null, null, array['Liver Health', 'Skin Disorders', 'Anti-inflammatory', 'Hepatoprotective'], null, null, array[]::text[], null, null),
('safed-musli-extract', 'Safed Musli Extract', 'safed-musli-extract', 'herbal-extracts', 'Chlorophytum borivilianum', 'Saponins 20%–40%', null, null, array['Male Vitality', 'Strength & Stamina', 'Aphrodisiac', 'Rejuvenation'], null, null, array[]::text[], null, null),
('salacia-extract', 'Salacia Extract', 'salacia-extract', 'herbal-extracts', 'Salacia oblonga/reticulata', 'Saponins 20%', null, null, array['Anti-diabetic support'], null, null, array[]::text[], null, null),
('sarsaparilla-extract', 'Sarsaparilla Extract', 'sarsaparilla-extract', 'herbal-extracts', 'Smilax ornata', 'Extract 4:1', null, null, array['Skin health', 'psoriasis'], null, null, array[]::text[], null, null),
('senna-leaf-extract', 'Senna Leaf Extract', 'senna-leaf-extract', 'herbal-extracts', 'Cassia angustifolia', 'Sennosides up to 60%', null, null, array['Laxative'], null, null, array[]::text[], null, null),
('sesame-seed-extract', 'Sesame Seed Extract', 'sesame-seed-extract', 'herbal-extracts', 'Sesamum indicum', 'Sesamin Complex 70%', null, null, array['Cardiovascular support'], null, null, array[]::text[], null, null),
('shatavari-extract', 'Shatavari Extract', 'shatavari-extract', 'herbal-extracts', 'Asparagus racemosus', 'Saponins 50%', null, null, array['Female wellness', 'adaptogen'], null, 'shatavari-extract.jpg', array[]::text[], null, null),
('shankhpushpi-extract', 'Shankhpushpi Extract', 'shankhpushpi-extract', 'herbal-extracts', 'Convolvulus pluricaulis', 'Alkaloids & Flavonoids 2%–5%', null, null, array['Brain Tonic', 'Memory Support', 'Stress Relief', 'Cognitive Wellness'], null, null, array[]::text[], null, null),
('saunf-extract', 'Saunf Extract', 'saunf-extract', 'herbal-extracts', 'Foeniculum vulgare', 'Volatile Oils 1%–2% (Anethole)', null, null, array['Digestive Support', 'Carminative', 'Bloating Relief', 'Hormonal Balance'], null, null, array[]::text[], null, null),
('shilajit-extract', 'Shilajit Extract', 'shilajit-extract', 'herbal-extracts', 'Asphaltum', 'Fulvic Acid 2–50%', null, null, array['Vitality and endurance'], null, null, array[]::text[], null, null),
('spinach-extract', 'Spinach Extract', 'spinach-extract', 'herbal-extracts', 'Spinacia oleracea', 'Nitrate 9%, Potassium 13%', null, null, array['Bone', 'skin', 'hair support'], null, 'spinach-extract.jpg', array[]::text[], null, null),
('tagar-extract', 'Tagar Extract', 'tagar-extract', 'herbal-extracts', 'Valeriana wallichii', 'Valepotriates 0.5%–1%', null, null, array['Sleep Support', 'Nervine Tonic', 'Stress Relief', 'Mild Sedative'], null, null, array[]::text[], null, null),
('tongkat-ali-extract', 'Tongkat Ali Extract', 'tongkat-ali-extract', 'herbal-extracts', 'Eurycoma longifolia', 'Eurycomanone 1%–2%', null, null, array['Testosterone Support', 'Male Vitality', 'Libido Enhancement', 'Energy & Stamina'], null, null, array[]::text[], null, null),
('triphala-extract', 'Triphala Extract', 'triphala-extract', 'herbal-extracts', 'Emblica officinalis, Terminalia bellirica, T. chebula', 'Tannins up to 45%', null, null, array['Digestive Cleanse', 'Antioxidant', 'Colon Health', 'Detoxification'], null, 'triphala.jpg', array[]::text[], null, null),
('trikatu-extract', 'Trikatu Extract', 'trikatu-extract', 'herbal-extracts', 'Piper nigrum, Piper longum, Zingiber officinale', 'Piperine 5%, Gingerols 2%', null, null, array['Digestive Support', 'Bioavailability Enhancer', 'Metabolism Booster', 'Respiratory Health'], null, null, array[]::text[], null, null),
('tulsi-holy-basil-extract', 'Tulsi (Holy Basil) Extract', 'tulsi-holy-basil-extract', 'herbal-extracts', 'Ocimum sanctum / Ocimum tenuiflorum', 'Ursolic Acid 2%–5%, Eugenol', null, null, array['Adaptogen', 'Respiratory Health', 'Antioxidant', 'Immunity Support'], null, null, array[]::text[], null, null),
('turmeric-extract', 'Turmeric Extract', 'turmeric-extract', 'herbal-extracts', 'Curcuma longa', 'Curcuminoids 95%', null, null, array['Anti-inflammatory', 'antioxidant'], null, 'turmeric-extract-powder-yellow.png', array[]::text[], null, null),
('valerian-extract', 'Valerian Extract', 'valerian-extract', 'herbal-extracts', 'Valeriana officinalis', 'Valerenic Acids 0.5%–1%', null, null, array['Sleep Support', 'Anxiety Relief', 'Nervine Tonic', 'Mild Sedative'], null, null, array[]::text[], null, null),
('varuna-extract', 'Varuna Extract', 'varuna-extract', 'herbal-extracts', 'Crataeva religiosa', 'Saponins 10%', null, null, array['Urinary health support'], null, null, array[]::text[], null, null),
('white-kidney-bean-extract', 'White Kidney Bean Extract', 'white-kidney-bean-extract', 'herbal-extracts', 'Phaseolus vulgaris', 'Phaseolamin 1%–2%', null, null, array['Starch Blocker', 'Weight Management', 'Carbohydrate Metabolism Support'], null, null, array[]::text[], null, null),
('yohimbine-hcl-extract', 'Yohimbine HCL Extract', 'yohimbine-hcl-extract', 'herbal-extracts', 'Pausinystalia yohimbe', '2%–98%', null, null, array['Male Vitality', 'Libido Enhancement', 'Fat Burning', 'Energy Support'], null, null, array[]::text[], null, null),
('clove-leaf-oil', 'Clove Leaf Oil', 'clove-leaf-oil', 'essential-oils', 'Syzygium aromaticum', 'Eugenol (80–85%)', null, null, array['Oral Care', 'Antiseptic', 'Flavoring', 'Pain Relief'], null, null, array[]::text[], null, null),
('cumin-seed-oil', 'Cumin Seed Oil', 'cumin-seed-oil', 'essential-oils', 'Cuminum cyminum', 'Cuminaldehyde (30–45%)', null, null, array['Digestive Aid', 'Flavoring', 'Antioxidant', 'Antimicrobial'], null, 'black-cumin-seed-oil.jpg', array[]::text[], null, null),
('eucalyptus-oil', 'Eucalyptus Oil', 'eucalyptus-oil', 'essential-oils', 'Eucalyptus globulus', 'Eucalyptol (Cineole) 70–85%', null, null, array['Respiratory Support', 'Antiseptic'], null, null, array[]::text[], null, null),
('frankincense-oil', 'Frankincense Oil', 'frankincense-oil', 'essential-oils', 'Boswellia serrata', 'α-Thujene up to 70%', null, null, array['Anti-inflammatory', 'Skincare', 'Aromatherapy', 'Stress Relief'], null, 'frankincense-oil.jpg', array[]::text[], null, null),
('garlic-oil', 'Garlic Oil', 'garlic-oil', 'essential-oils', 'Allium sativum', 'Allicin (varies, unstable), Diallyl disulfide (~50–60%) & Diallyl trisulfide (~10–15%)', null, null, array['Antimicrobial', 'Cardiovascular Support', 'Immune Booster', 'Flavoring'], null, 'garlic-oil.jpg', array[]::text[], null, null),
('ginger-oil', 'Ginger Oil', 'ginger-oil', 'essential-oils', 'Zingiber officinale', 'Zingiberene (~30–35%)', null, null, array['Digestive Aid', 'Anti-inflammatory', 'Muscle Relief', 'Aromatherapy'], null, 'ginger-oil.jpg', array[]::text[], null, null),
('lemon-grass-oil', 'Lemon Grass Oil', 'lemon-grass-oil', 'essential-oils', 'Cymbopogon citratus', 'Citral (neral + geranial) ~70–80%', null, null, array['Antimicrobial', 'Aromatherapy', 'Insect Repellent', 'Flavoring', 'Perfumery'], null, 'lemon-grass-oil.jpg', array[]::text[], null, null),
('nutmeg-oil', 'Nutmeg Oil', 'nutmeg-oil', 'essential-oils', 'Myristica fragrans', 'Myristicin ~10–15%, Safrole ~5–10%', null, null, array['Digestive Aid', 'Aromatherapy', 'Flavoring', 'Antimicrobial'], null, null, array[]::text[], null, null),
('turmeric-oil', 'Turmeric Oil', 'turmeric-oil', 'essential-oils', 'Curcuma longa', 'Turmerone (~40–50%), Ar-turmerone (~10–15%)', null, null, array['Anti-inflammatory', 'Antioxidant', 'Skin Care', 'Aromatherapy'], null, 'turmeric-oil.jpg', array[]::text[], null, null),
('white-pepper-oil', 'White Pepper Oil', 'white-pepper-oil', 'essential-oils', 'Piper nigrum', 'Limonene (~30–45%), Sabinene (~20–30%)', null, null, array['Flavoring', 'Digestive Aid', 'Anti-inflammatory', 'Aromatherapy'], null, null, array[]::text[], null, null),
('black-pepper-oil', 'Black Pepper Oil', 'black-pepper-oil', 'essential-oils', 'Piper nigrum', 'β-Caryophyllene (~25–35%)', null, null, array['Digestive Aid', 'Anti-inflammatory', 'Pain Relief', 'Flavoring', 'Aromatherapy'], null, 'black-pepper-oil.jpg', array[]::text[], null, null),
('lavender-oil', 'Lavender Oil', 'lavender-oil', 'essential-oils', 'Lavandula angustifolia', 'Linalool (~25–45%)', null, null, array['Relaxation', 'Aromatherapy', 'Skincare', 'Antimicrobial'], null, null, array[]::text[], null, null),
('peppermint-oil', 'Peppermint Oil', 'peppermint-oil', 'essential-oils', 'Mentha piperita', 'Menthol (~30–55%)', null, null, array['Digestive Aid', 'Cooling Sensation', 'Aromatherapy', 'Pain Relief'], null, null, array[]::text[], null, null),
('tea-tree-oil', 'Tea Tree Oil', 'tea-tree-oil', 'essential-oils', 'Melaleuca alternifolia', 'Terpinen-4-ol (~30–40%)', null, null, array['Antimicrobial', 'Antiseptic', 'Skincare', 'Acne Treatment'], null, null, array[]::text[], null, null),
('moringa-oil', 'Moringa oil', 'moringa-oil', 'essential-oils', 'Moringa oleifera', 'Oleic Acid (~70–75%), Palmitic Acid (~6–8%)', null, null, array['Skin Moisturizer', 'Anti-inflammatory', 'Hair Care', 'Antioxidant'], null, null, array[]::text[], null, null),
('vetiver-oil', 'Vetiver Oil', 'vetiver-oil', 'essential-oils', 'Vetiveria zizanoides', 'Khusimol (~15–20%), Vetiselinenol (~10–15%)', null, null, array['Aromatherapy', 'Perfumes', 'Stress Relief', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('neroli-oil', 'Neroli Oil', 'neroli-oil', 'essential-oils', 'Citrus aurantium (Bitter Orange)', 'Linalool (~30–40%), Limonene (~10–20%)', null, null, array['Aromatherapy', 'Relaxation', 'Skincare', 'Perfumes'], null, null, array[]::text[], null, null),
('bergamot-oil', 'Bergamot Oil', 'bergamot-oil', 'essential-oils', 'Citrus bergamia', 'Limonene (~30–45%), Linalyl acetate (~15–25%)', null, null, array['Aromatherapy', 'Mood Enhancer', 'Skincare', 'Flavoring'], null, null, array[]::text[], null, null),
('patchouli-oil', 'Patchouli Oil', 'patchouli-oil', 'essential-oils', 'Pogostemon cablin', 'Patchoulol (Patchouli alcohol) (~30–40%)', null, null, array['Aromatherapy', 'Perfumery', 'Anti-inflammatory', 'Skin Care'], null, null, array[]::text[], null, null),
('rose-oil', 'Rose oil', 'rose-oil', 'essential-oils', 'Rosa damascene', 'Citronellol (~20–30%)', null, null, array['Aromatherapy', 'Skincare', 'Mood Enhancer', 'Perfumery'], null, null, array[]::text[], null, null),
('black-pepper-oleoresin', 'Black Pepper Oleoresin', 'black-pepper-oleoresin', 'oleoresins', 'Piper nigrum', 'Piperine (~70–80%)', null, null, array['Flavoring', 'Bioavailability Enhancer', 'Antioxidant'], null, 'black-pepper-oleoresin-bottle.png', array[]::text[], null, null),
('capsicum-oleoresin', 'Capsicum Oleoresin', 'capsicum-oleoresin', 'oleoresins', 'Capsicum annuum', 'Capsaicinoids (~60–90%)', null, null, array['Spice', 'Pharmaceutical', 'Topical Analgesic'], null, 'capsicum-oleoresin-bottle.png', array[]::text[], null, null),
('cinnamon-oleoresin', 'Cinnamon Oleoresin', 'cinnamon-oleoresin', 'oleoresins', 'Cinnamomum verum / Cinnamomum cassia', 'Cinnamaldehyde (~50–65%)', null, null, array['Flavoring', 'Antimicrobial', 'Food Preservation', 'Pharmaceutical'], null, 'cinnamon-oleoresin-bottle.png', array[]::text[], null, null),
('coffee-oleoresin', 'Coffee Oleoresin', 'coffee-oleoresin', 'oleoresins', 'Coffea arabica', 'Caffeine (~0.5–2%)', null, null, array['Flavoring', 'Fragrance', 'Cosmetics', 'Nutraceuticals'], null, null, array[]::text[], null, null),
('coriander-oleoresin', 'Coriander Oleoresin', 'coriander-oleoresin', 'oleoresins', 'Coriandrum sativum', 'Linalool (~60–75%), α-Pinene (~5–10%)', null, null, array['Flavoring', 'Digestive Aid', 'Fragrance', 'Antimicrobial'], null, null, array[]::text[], null, null),
('clove-oleoresin', 'Clove Oleoresin', 'clove-oleoresin', 'oleoresins', 'Syzygium aromaticum', 'Eugenol (~65–75%), β-Caryophyllene (~15–20%)', null, null, array['Flavoring', 'Antimicrobial', 'Oral Care', 'Pharmaceutical'], null, null, array[]::text[], null, null),
('cumin-oleoresin', 'Cumin Oleoresin', 'cumin-oleoresin', 'oleoresins', 'Cuminum cyminum', 'Cuminaldehyde (~25–35%)', null, null, array['Flavoring', 'Digestive Aid', 'Aromatherapy', 'Antioxidant'], null, null, array[]::text[], null, null),
('dill-seed-oleoresin', 'Dill Seed Oleoresin', 'dill-seed-oleoresin', 'oleoresins', 'Anethum graveolens', 'Carvone (~40–60%), Limonene (~30–40%)', null, null, array['Flavoring', 'Digestive Support', 'Antispasmodic', 'Aromatherapy'], null, null, array[]::text[], null, null),
('fennel-oleoresin', 'Fennel Oleoresin', 'fennel-oleoresin', 'oleoresins', 'Foeniculum vulgare', 'Anethole (~60–80%), Fenchone (~5–10%)', null, null, array['Flavoring', 'Digestive Aid', 'Carminative', 'Aromatherapy'], null, null, array[]::text[], null, null),
('fenugreek-oleoresin', 'Fenugreek Oleoresin', 'fenugreek-oleoresin', 'oleoresins', 'Trigonella foenumgraecum', 'Sotolon (~0.5–1.5%)', null, null, array['Flavoring', 'Lactation Support', 'Nutraceuticals', 'Ayurvedic Formulations'], null, null, array[]::text[], null, null),
('garlic-oleoresin', 'Garlic Oleoresin', 'garlic-oleoresin', 'oleoresins', 'Allium sativum', 'Diallyl disulfide (~50–60%), Diallyl trisulfide (~15–25%)', null, null, array['Flavoring', 'Antimicrobial', 'Food Processing', 'Nutraceuticals'], null, null, array[]::text[], null, null),
('ginger-oleoresin', 'Ginger Oleoresin', 'ginger-oleoresin', 'oleoresins', 'Zingiber officinale', 'Gingerols (~15–25%), Shogaols (~5–10%)', null, null, array['Flavoring', 'Digestive Aid', 'Pharmaceutical'], null, 'ginger-oleoresin-bottle.png', array[]::text[], null, null),
('hing-oleoresin', 'Hing Oleoresin', 'hing-oleoresin', 'oleoresins', 'Ferula asafoetida', 'Ferulic acid (~10–20%)', null, null, array['Digestive Aid', 'Antispasmodic', 'Flavoring', 'Ayurvedic Medicine'], null, null, array[]::text[], null, null),
('mace-oleoresin', 'Mace Oleoresin', 'mace-oleoresin', 'oleoresins', 'Myristica fragrans', 'Myristicin (~4–10%), Elemicin (~5–8%)', null, null, array['Flavoring', 'Perfumery', 'Digestive Aid', 'Pharmaceutical Use'], null, null, array[]::text[], null, null),
('nutmeg-oleoresin', 'Nutmeg Oleoresin', 'nutmeg-oleoresin', 'oleoresins', 'Myristica fragrans', 'Myristicin (~5–15%), Elemicin (~5–10%)', null, null, array['Flavoring', 'Aromatherapy', 'Digestive Aid', 'Pharmaceutical Formulations'], null, null, array[]::text[], null, null),
('onion-oleoresin', 'Onion Oleoresin', 'onion-oleoresin', 'oleoresins', 'Allium cepa', 'Dipropyl disulfide (~15–25%)', null, null, array['Flavoring', 'Antimicrobial', 'Food Processing', 'Nutraceuticals'], null, null, array[]::text[], null, null),
('paprika-oleoresin', 'Paprika Oleoresin', 'paprika-oleoresin', 'oleoresins', 'Capsicum annuum', 'Capsaicin (~3–6%), Capsanthin (~50–60%)', null, null, array['Natural Coloring', 'Flavoring', 'Antioxidant', 'Food Industry'], null, null, array[]::text[], null, null),
('turmeric-oleoresin', 'Turmeric Oleoresin', 'turmeric-oleoresin', 'oleoresins', 'Curcuma longa', 'Curcuminoids (~10–20%), Turmerones (~30–40%)', null, null, array['Natural Coloring', 'Anti-inflammatory', 'Food & Beverage'], null, 'turmeric-oleoresin-bottle.png', array[]::text[], null, null),
('white-pepper-oleoresin', 'White Pepper Oleoresin', 'white-pepper-oleoresin', 'oleoresins', 'Piper nigrum', 'Piperine (~70–80%)', null, null, array['Flavoring', 'Digestive Aid', 'Food Preservation', 'Pharmaceutical'], null, null, array[]::text[], null, null),
('amla-juice-powder', 'Amla Juice Powder', 'amla-juice-powder', 'fruit-juice-powders', 'Emblica officinalis', 'Tannins, Vitamin C', null, null, array['Rejuvenation', 'Skin & Hair Care'], null, 'amla-juice-powder-green.png', array[]::text[], null, null),
('apple-juice-powder', 'Apple Juice Powder', 'apple-juice-powder', 'fruit-juice-powders', 'Malus domestica', 'Natural Sugars, Polyphenols', null, null, array['Antioxidant', 'Energy Support', 'Flavoring'], null, null, array[]::text[], null, null),
('banana-pulp-powder', 'Banana Pulp/Powder', 'banana-pulp-powder', 'fruit-juice-powders', 'Musa paradisiaca', 'Potassium, Natural Sugars', null, null, array['Energy', 'Digestion', 'Smoothie Additive'], null, null, array[]::text[], null, null),
('beet-root-juice-powder', 'Beet Root Juice Powder', 'beet-root-juice-powder', 'fruit-juice-powders', 'Beta vulgaris', 'Betanin, Nitrates', null, null, array['Cardiovascular Health', 'Energy', 'Coloring'], null, null, array[]::text[], null, null),
('coconut-water-powder', 'Coconut Water Powder', 'coconut-water-powder', 'fruit-juice-powders', 'Cocos nucifera', 'Electrolytes, Potassium', null, null, array['Hydration', 'Sports Nutrition'], null, null, array[]::text[], null, null),
('custard-apple-powder', 'Custard Apple Powder', 'custard-apple-powder', 'fruit-juice-powders', 'Annona reticulata (est.)', 'Natural Sugars, Vitamins', null, null, array['Energy', 'Nutraceutical Formulations'], null, null, array[]::text[], null, null),
('date-fruit-powder', 'Date Fruit Powder', 'date-fruit-powder', 'fruit-juice-powders', 'Phoenix dactylifera', 'Glucose, Fiber, Polyphenols', null, null, array['Energy Support', 'Digestive Health'], null, null, array[]::text[], null, null),
('guava-powder', 'Guava Powder', 'guava-powder', 'fruit-juice-powders', 'Psidium guajava', 'Vitamin C, Fiber', null, null, array['Immunity', 'Gut Health'], null, null, array[]::text[], null, null),
('jamun-powder', 'Jamun Powder', 'jamun-powder', 'fruit-juice-powders', 'Syzygium cumini', 'Anthocyanins, Jamboline', null, null, array['Blood Sugar Management', 'Antioxidant'], null, null, array[]::text[], null, null),
('kiwi-powder', 'Kiwi Powder', 'kiwi-powder', 'fruit-juice-powders', 'Actinidia deliciosa', 'Actinidin, Vitamin C', null, null, array['Skin Care', 'Immunity Support'], null, null, array[]::text[], null, null),
('lemon-juice-powder', 'Lemon Juice/Powder', 'lemon-juice-powder', 'fruit-juice-powders', 'Citrus limon', 'Citric Acid, Ascorbic Acid', null, null, array['Digestive Support', 'Immunity', 'Detox'], null, null, array[]::text[], null, null),
('litchi-powder', 'Litchi Powder', 'litchi-powder', 'fruit-juice-powders', 'Litchi chinensis', 'Vitamin C, Oligonol', null, null, array['Anti-aging', 'Energy', 'Flavoring'], null, null, array[]::text[], null, null),
('mango-juice-powder', 'Mango Juice/Powder', 'mango-juice-powder', 'fruit-juice-powders', 'Mangifera indica', 'Carotenoids, Vitamin C', null, null, array['Immune Health', 'Skin Rejuvenation', 'Flavoring'], null, 'mango-juice-powder-yellow.png', array[]::text[], null, null),
('orange-juice-powder', 'Orange Juice/Powder', 'orange-juice-powder', 'fruit-juice-powders', 'Citrus sinensis', 'Vitamin C, Flavonoids', null, null, array['Immunity Support', 'Antioxidant', 'Flavoring'], null, 'orange-juice-powder.png', array[]::text[], null, null),
('papaya-powder', 'Papaya Powder', 'papaya-powder', 'fruit-juice-powders', 'Carica papaya', 'Papain, Beta-Carotene', null, null, array['Digestive Enzyme Support'], null, null, array[]::text[], null, null),
('peach-powder', 'Peach Powder', 'peach-powder', 'fruit-juice-powders', 'Prunus persica', 'Carotenoids', null, null, array['Skin Health', 'Beverage Additive'], null, null, array[]::text[], null, null),
('pineapple-juice-powder', 'Pineapple Juice/Powder', 'pineapple-juice-powder', 'fruit-juice-powders', 'Ananas comosus', 'Bromelain, Vitamin C', null, null, array['Digestive Aid', 'Anti-inflammatory', 'Flavoring'], null, null, array[]::text[], null, null),
('pomegranate-juice-powder', 'Pomegranate Juice/Powder', 'pomegranate-juice-powder', 'fruit-juice-powders', 'Punica granatum', 'Ellagic Acid, Polyphenols', null, null, array['Antioxidant', 'Heart & Cardiovascular Support'], null, 'pomegranate-juice-powder-red.png', array[]::text[], null, null),
('sapota-chikoo-powder', 'Sapota (Chikoo) Powder', 'sapota-chikoo-powder', 'fruit-juice-powders', 'Manilkara zapota', 'Polyphenols, Sugars', null, null, array['Energy', 'Flavoring', 'Smoothie Base'], null, null, array[]::text[], null, null),
('strawberry-juice-powder', 'Strawberry Juice/Powder', 'strawberry-juice-powder', 'fruit-juice-powders', 'Fragaria × ananassa', 'Anthocyanins, Vit-C', null, null, array['Skin Health', 'Antioxidant', 'Natural Coloring'], null, null, array[]::text[], null, null),
('tamarind-pulp-powder', 'Tamarind Pulp Powder', 'tamarind-pulp-powder', 'fruit-juice-powders', 'Tamarindus indica', 'Tartaric Acid, Polyphenols', null, null, array['Digestive Aid', 'Flavoring'], null, null, array[]::text[], null, null),
('watermelon-juice-powder', 'Watermelon Juice/Powder', 'watermelon-juice-powder', 'fruit-juice-powders', 'Citrullus lanatus', 'Lycopene, Citrulline', null, null, array['Hydration', 'Antioxidant', 'Skin Health'], null, null, array[]::text[], null, null),
('5-hydroxytryptophan-5-htp', '5-Hydroxytryptophan (5-HTP)', '5-hydroxytryptophan-5-htp', 'phytochemicals', 'Griffonia simplicifolia', '5-HTP', null, null, array['Mood Support', 'Sleep Aid'], null, null, array[]::text[], null, null),
('berberine-hcl', 'Berberine HCL', 'berberine-hcl', 'phytochemicals', 'Berberis aristata', 'Berberine', null, null, array['Blood Sugar & Lipid Regulation'], null, 'berberine-hcl-powder.png', array[]::text[], null, null),
('beta-aescin', 'Beta Aescin', 'beta-aescin', 'phytochemicals', 'Aesculus hippocastanum', 'Aescin', null, null, array['Venous Support', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('colchicine', 'Colchicine', 'colchicine', 'phytochemicals', 'Gloriosa superba', 'Colchicine', null, null, array['Anti-Gout', 'Anti-Inflammatory'], null, null, array[]::text[], null, null),
('curcumin', 'Curcumin', 'curcumin', 'phytochemicals', 'Curcuma longa', 'Curcuminoids', null, null, array['Antioxidant', 'Anti-inflammatory'], null, 'curcumin-powder-yellow.png', array[]::text[], null, null),
('forskolin', 'Forskolin', 'forskolin', 'phytochemicals', 'Coleus forskohlii', 'Forskolin', null, null, array['Weight Management', 'Cardiovascular Health'], null, null, array[]::text[], null, null),
('natural-caffeine', 'Natural Caffeine', 'natural-caffeine', 'phytochemicals', 'Coffea robusta / Camellia sinensis', 'Caffeine', null, null, array['Energy', 'Alertness', 'Thermogenic'], null, 'natural-caffeine-powder.png', array[]::text[], null, null),
('piperine', 'Piperine', 'piperine', 'phytochemicals', 'Piper nigrum', 'Piperine', null, null, array['Bioavailability Enhancer', 'Thermogenic'], null, 'piperine-extract.jpg', array[]::text[], null, null),
('quercetin-dihydrate', 'Quercetin Dihydrate', 'quercetin-dihydrate', 'phytochemicals', 'Sophora japonica', 'Quercetin', null, null, array['Antioxidant', 'Allergy Relief'], null, null, array[]::text[], null, null),
('resveratrol', 'Resveratrol', 'resveratrol', 'phytochemicals', 'Vitis vinifera', 'Resveratrol', null, null, array['Anti-aging', 'Cardiovascular Support'], null, 'resveratrol-powder-white.png', array[]::text[], null, null),
('rutin', 'Rutin', 'rutin', 'phytochemicals', 'Sophora japonica (est.)', 'Rutin', null, null, array['Capillary Strength', 'Antioxidant'], null, null, array[]::text[], null, null),
('thiocolchicoside', 'Thiocolchicoside', 'thiocolchicoside', 'phytochemicals', 'Gloriosa superba', 'Thiocolchicoside', null, null, array['Muscle Relaxant'], null, null, array[]::text[], null, null),
('vinpocetine', 'Vinpocetine', 'vinpocetine', 'phytochemicals', 'Voacanga africana', 'Vinpocetine', null, null, array['Cognitive Support', 'Neuroprotection'], null, null, array[]::text[], null, null),
('yohimbine-hcl', 'Yohimbine HCL', 'yohimbine-hcl', 'phytochemicals', 'Pausinystalia yohimbe', 'Yohimbine', null, null, array['Libido Support', 'Fat Loss Aid'], null, null, array[]::text[], null, null),
('acetyl-l-carnitine-hcl', 'Acetyl L-Carnitine HCL', 'acetyl-l-carnitine-hcl', 'amino-acids', 'Synthetic', 'Acetyl L-Carnitine', null, null, array['Cognitive Support', 'Fat Metabolism'], null, null, array[]::text[], null, null),
('acetyl-l-tyrosine', 'Acetyl L-Tyrosine', 'acetyl-l-tyrosine', 'amino-acids', 'Synthetic', 'Acetyl L-Tyrosine', null, null, array['Mental Focus', 'Stress Adaptation'], null, null, array[]::text[], null, null),
('bcaa-blend-instant', 'BCAA Blend / Instant', 'bcaa-blend-instant', 'amino-acids', 'Fermentation', 'Leucine, Isoleucine, Valine', null, null, array['Muscle Recovery', 'Endurance'], null, null, array[]::text[], null, null),
('beta-alanine', 'Beta Alanine', 'beta-alanine', 'amino-acids', 'Synthetic', 'Beta Alanine', null, null, array['Muscle Carnosine Booster', 'Performance'], null, null, array[]::text[], null, null),
('creatine-monohydrate', 'Creatine Monohydrate', 'creatine-monohydrate', 'amino-acids', 'Synthetic', 'Creatine', null, null, array['Strength', 'Muscle Volume'], null, null, array[]::text[], null, null),
('l-carnosine', 'L-Carnosine', 'l-carnosine', 'amino-acids', 'Beta-alanine + L-histidine', 'Carnosine', null, null, array['Anti-aging', 'Muscle & Brain Health'], null, null, array[]::text[], null, null),
('l-cysteine-base-hcl', 'L-Cysteine Base / HCL', 'l-cysteine-base-hcl', 'amino-acids', 'Fermentation', 'L-Cysteine', null, null, array['Antioxidant', 'Skin & Hair Health'], null, null, array[]::text[], null, null),
('l-cystine', 'L-Cystine', 'l-cystine', 'amino-acids', 'Fermentation', 'L-Cystine', null, null, array['Protein Synthesis', 'Detoxification'], null, null, array[]::text[], null, null),
('l-glutamic-acid', 'L-Glutamic Acid', 'l-glutamic-acid', 'amino-acids', 'Fermentation', 'L-Glutamic Acid', null, null, array['Neurotransmitter Support'], null, null, array[]::text[], null, null),
('l-theanine', 'L-Theanine', 'l-theanine', 'amino-acids', 'Camellia sinensis', 'L-Theanine', null, null, array['Relaxation', 'Cognitive Clarity'], null, 'l-theanine-powder-white.png', array[]::text[], null, null),
('l-threonine', 'L-Threonine', 'l-threonine', 'amino-acids', 'Fermentation', 'L-Threonine', null, null, array['Protein Synthesis', 'Gut Health'], null, null, array[]::text[], null, null),
('l-tryptophan', 'L-Tryptophan', 'l-tryptophan', 'amino-acids', 'Fermentation', 'L-Tryptophan', null, null, array['Serotonin Precursor', 'Sleep Support'], null, null, array[]::text[], null, null),
('l-tyrosine', 'L-Tyrosine', 'l-tyrosine', 'amino-acids', 'Fermentation', 'L-Tyrosine', null, null, array['Dopamine Precursor', 'Mood Balance'], null, null, array[]::text[], null, null),
('l-valine', 'L-Valine', 'l-valine', 'amino-acids', 'Fermentation', 'L-Valine', null, null, array['Muscle Repair', 'Energy'], null, null, array[]::text[], null, null),
('l-arginine-hcl-akg', 'L-Arginine HCL / AKG', 'l-arginine-hcl-akg', 'amino-acids', 'Fermentation', 'L-Arginine', null, null, array['Nitric Oxide Booster', 'Circulation'], null, null, array[]::text[], null, null),
('l-arginine-l-aspartate', 'L-Arginine L-Aspartate', 'l-arginine-l-aspartate', 'amino-acids', 'Fermentation', 'Arginine + Aspartic Acid', null, null, array['Endurance', 'Detoxification'], null, null, array[]::text[], null, null),
('l-leucine', 'L-Leucine', 'l-leucine', 'amino-acids', 'Fermentation', 'L-Leucine', null, null, array['Muscle Protein Synthesis'], null, null, array[]::text[], null, null),
('l-lysine-mono-acetate-aspartate', 'L-Lysine (Mono / Acetate / Aspartate)', 'l-lysine-mono-acetate-aspartate', 'amino-acids', 'Fermentation', 'L-Lysine', null, null, array['Collagen Support', 'Immunity'], null, null, array[]::text[], null, null),
('l-malic-acid', 'L-Malic Acid', 'l-malic-acid', 'amino-acids', 'Natural Source', 'Malic Acid', null, null, array['Energy Production', 'Detoxification'], null, null, array[]::text[], null, null),
('l-methionine-dl-methionine', 'L-Methionine / DL-Methionine', 'l-methionine-dl-methionine', 'amino-acids', 'Fermentation / Synthetic', 'Methionine', null, null, array['Liver Health', 'Antioxidant'], null, null, array[]::text[], null, null),
('l-methyl-folate-calcium', 'L-Methyl Folate Calcium', 'l-methyl-folate-calcium', 'amino-acids', 'Synthetic', 'L-5-MTHF', null, null, array['Methylation', 'Mood & Neural Support'], null, null, array[]::text[], null, null),
('l-ornithine-hcl-aspartate', 'L-Ornithine (HCL / Aspartate)', 'l-ornithine-hcl-aspartate', 'amino-acids', 'Fermentation', 'L-Ornithine', null, null, array['Detoxification', 'Liver Health'], null, null, array[]::text[], null, null),
('l-phenylalanine', 'L-Phenylalanine', 'l-phenylalanine', 'amino-acids', 'Fermentation', 'L-Phenylalanine', null, null, array['Mood Support', 'Neurotransmitter Precursor'], null, null, array[]::text[], null, null),
('l-proline', 'L-Proline', 'l-proline', 'amino-acids', 'Fermentation', 'L-Proline', null, null, array['Collagen Formation', 'Skin Health'], null, null, array[]::text[], null, null),
('l-serine', 'L-Serine', 'l-serine', 'amino-acids', 'Fermentation', 'L-Serine', null, null, array['Brain Function', 'Immune Support'], null, null, array[]::text[], null, null),
('l-taurine', 'L-Taurine', 'l-taurine', 'amino-acids', 'Synthetic', 'Taurine', null, null, array['Cardiovascular & Eye Health'], null, null, array[]::text[], null, null),
('l-citrulline-dl-malate', 'L-Citrulline DL-Malate', 'l-citrulline-dl-malate', 'amino-acids', 'Fermentation', 'Citrulline + Malic Acid', null, null, array['Endurance', 'Muscle Recovery'], null, null, array[]::text[], null, null),
('l-glutathione-reduced', 'L-Glutathione Reduced', 'l-glutathione-reduced', 'amino-acids', 'Fermentation', 'Glutathione', null, null, array['Antioxidant', 'Detox'], null, null, array[]::text[], null, null),
('alpha-lipoic-acid', 'Alpha Lipoic Acid', 'alpha-lipoic-acid', 'nutraceuticals', 'Synthetic', 'Alpha Lipoic Acid', null, null, array['Antioxidant', 'Nerve Health'], null, null, array[]::text[], null, null),
('arbutin', 'Arbutin', 'arbutin', 'nutraceuticals', 'Bearberry (Arctostaphylos uva-ursi)', 'Arbutin', null, null, array['Skin Brightening', 'Pigmentation Control'], null, null, array[]::text[], null, null),
('astaxanthin-10', 'Astaxanthin 10%', 'astaxanthin-10', 'nutraceuticals', 'Haematococcus pluvialis', 'Astaxanthin', null, null, array['Eye Health', 'Anti-aging'], null, null, array[]::text[], null, null),
('barley-grass-powder', 'Barley Grass Powder', 'barley-grass-powder', 'nutraceuticals', 'Hordeum vulgare', 'Chlorophyll, Vitamins', null, null, array['Detoxification', 'Alkalizing Agent'], null, null, array[]::text[], null, null),
('beta-carotene-10-30', 'Beta Carotene (10% / 30%)', 'beta-carotene-10-30', 'nutraceuticals', 'Daucus carota / Dunaliella salina', 'Beta Carotene', null, null, array['Eye Health', 'Antioxidant'], null, null, array[]::text[], null, null),
('bovine-colostrum', 'Bovine Colostrum', 'bovine-colostrum', 'nutraceuticals', 'Bovine Milk', 'Immunoglobulins, Growth Factors', null, null, array['Immunity', 'Gut Health'], null, null, array[]::text[], null, null),
('calcitriol', 'Calcitriol', 'calcitriol', 'nutraceuticals', 'Synthetic', 'Active Vitamin D3', null, null, array['Bone Health', 'Calcium Absorption'], null, null, array[]::text[], null, null),
('coenzyme-q10-ubiquinone', 'Coenzyme Q10 (Ubiquinone)', 'coenzyme-q10-ubiquinone', 'nutraceuticals', 'Fermentation', 'CoQ10', null, null, array['Heart Health', 'Energy Production'], null, null, array[]::text[], null, null),
('collagen-peptide-bovine', 'Collagen Peptide (Bovine)', 'collagen-peptide-bovine', 'nutraceuticals', 'Bovine Source', 'Type I & III Collagen', null, null, array['Skin', 'Joint & Hair Health'], null, null, array[]::text[], null, null),
('collagen-peptide-marine', 'Collagen Peptide (Marine)', 'collagen-peptide-marine', 'nutraceuticals', 'Marine Source', 'Type I Collagen', null, null, array['Skin Elasticity', 'Anti-aging'], null, null, array[]::text[], null, null),
('conjugated-linoleic-acid', 'Conjugated Linoleic Acid', 'conjugated-linoleic-acid', 'nutraceuticals', 'Safflower Oil', 'CLA', null, null, array['Fat Metabolism', 'Weight Management'], null, null, array[]::text[], null, null),
('d-biotin', 'D-Biotin', 'd-biotin', 'nutraceuticals', 'Synthetic', 'Biotin', null, null, array['Hair', 'Skin & Nail Health'], null, null, array[]::text[], null, null),
('d-chiro-inositol', 'D-Chiro Inositol', 'd-chiro-inositol', 'nutraceuticals', 'Synthetic', 'DCI', null, null, array['PCOS Support', 'Insulin Sensitivity'], null, null, array[]::text[], null, null),
('dha-veg-10-40', 'DHA Veg (10% / 40%)', 'dha-veg-10-40', 'nutraceuticals', 'Algal Source', 'Docosahexaenoic Acid', null, null, array['Brain & Eye Development'], null, null, array[]::text[], null, null),
('folic-acid', 'Folic Acid', 'folic-acid', 'nutraceuticals', 'Synthetic', 'Vitamin B9', null, null, array['Prenatal Health', 'Cell Division'], null, null, array[]::text[], null, null),
('glutathione-reduced', 'Glutathione Reduced', 'glutathione-reduced', 'nutraceuticals', 'Fermentation', 'Glutathione', null, null, array['Antioxidant', 'Skin Brightening'], null, null, array[]::text[], null, null),
('grape-seed-extract', 'Grape Seed Extract', 'grape-seed-extract', 'nutraceuticals', 'Vitis vinifera', 'Proanthocyanidins', null, null, array['Antioxidant', 'Cardiovascular Support'], null, null, array[]::text[], null, null),
('inositol', 'Inositol', 'inositol', 'nutraceuticals', 'Synthetic', 'Inositol', null, null, array['Mood Balance', 'Hormonal Health'], null, null, array[]::text[], null, null),
('lutein-10-20-40', 'Lutein (10% / 20% / 40%)', 'lutein-10-20-40', 'nutraceuticals', 'Tagetes erecta', 'Lutein', null, null, array['Eye Health', 'Blue Light Protection'], null, null, array[]::text[], null, null),
('lycopene-10-powder-liquid', 'Lycopene (10% Powder / Liquid)', 'lycopene-10-powder-liquid', 'nutraceuticals', 'Solanum lycopersicum', 'Lycopene', null, null, array['Prostate Health', 'Antioxidant'], null, null, array[]::text[], null, null),
('marine-collagen', 'Marine Collagen', 'marine-collagen', 'nutraceuticals', 'Fish Source', 'Type I Collagen', null, null, array['Skin', 'Hair & Joint Support'], null, null, array[]::text[], null, null),
('methyl-folate-calcium', 'Methyl Folate Calcium', 'methyl-folate-calcium', 'nutraceuticals', 'Synthetic', 'L-5-MTHF', null, null, array['Methylation', 'Mood & Neural Support'], null, null, array[]::text[], null, null),
('methyl-sulfonyl-methane-msm', 'Methyl Sulfonyl Methane (MSM)', 'methyl-sulfonyl-methane-msm', 'nutraceuticals', 'Synthetic', 'MSM', null, null, array['Joint Health', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('myo-inositol', 'Myo-Inositol', 'myo-inositol', 'nutraceuticals', 'Synthetic', 'Myo-Inositol', null, null, array['Fertility', 'PCOS Support'], null, null, array[]::text[], null, null),
('nano-curcumin', 'Nano Curcumin', 'nano-curcumin', 'nutraceuticals', 'Curcuma longa', 'Curcuminoids (Nanoform)', null, null, array['Enhanced Bioavailability', 'Inflammation Support'], null, null, array[]::text[], null, null),
('omega-3-fatty-acids-epa-dha', 'Omega-3 Fatty Acids (EPA/DHA)', 'omega-3-fatty-acids-epa-dha', 'nutraceuticals', 'Fish / Algal Source', 'EPA:DHA (various ratios)', null, null, array['Heart', 'Brain & Joint Health'], null, null, array[]::text[], null, null),
('pancreatin', 'Pancreatin', 'pancreatin', 'nutraceuticals', 'Porcine Source', 'Digestive Enzymes', null, null, array['Digestive Support'], null, null, array[]::text[], null, null),
('pea-protein', 'Pea Protein', 'pea-protein', 'nutraceuticals', 'Pisum sativum', 'Plant Protein', null, null, array['Muscle Growth', 'Vegan Nutrition'], null, null, array[]::text[], null, null),
('phytosterols', 'Phytosterols', 'phytosterols', 'nutraceuticals', 'Plant Oils', 'Beta-Sitosterol & Others', null, null, array['Cholesterol Management'], null, null, array[]::text[], null, null),
('raspberry-ketones-98', 'Raspberry Ketones 98%', 'raspberry-ketones-98', 'nutraceuticals', 'Rubus idaeus', 'Raspberry Ketone', null, null, array['Weight Management', 'Metabolism Booster'], null, null, array[]::text[], null, null),
('resveratrol-50-98', 'Resveratrol (50% / 98%)', 'resveratrol-50-98', 'nutraceuticals', 'Polygonum cuspidatum / Vitis vinifera', 'Resveratrol', null, null, array['Anti-aging', 'Cardiovascular Support'], null, null, array[]::text[], null, null),
('s-adenosyl-l-methionine-same', 'S-Adenosyl L-Methionine (SAMe)', 's-adenosyl-l-methionine-same', 'nutraceuticals', 'Synthetic', 'SAMe', null, null, array['Mood Support', 'Liver Health'], null, null, array[]::text[], null, null),
('sodium-hyaluronate', 'Sodium Hyaluronate', 'sodium-hyaluronate', 'nutraceuticals', 'Fermentation', 'Hyaluronic Acid', null, null, array['Joint Lubrication', 'Skin Hydration'], null, null, array[]::text[], null, null),
('soya-lecithin-powder', 'Soya Lecithin Powder', 'soya-lecithin-powder', 'nutraceuticals', 'Glycine max', 'Phospholipids', null, null, array['Brain Health', 'Emulsifier'], null, null, array[]::text[], null, null),
('spirulina-powder', 'Spirulina Powder', 'spirulina-powder', 'nutraceuticals', 'Arthrospira platensis', 'Phycocyanin, Protein', null, null, array['Detox', 'Energy', 'Antioxidant'], null, null, array[]::text[], null, null),
('tetrahydrocurcumin', 'Tetrahydrocurcumin', 'tetrahydrocurcumin', 'nutraceuticals', 'Curcuma longa', 'Tetrahydrocurcumin', null, null, array['Skin Brightening', 'Anti-inflammatory'], null, null, array[]::text[], null, null),
('ubiquinol-acetate', 'Ubiquinol Acetate', 'ubiquinol-acetate', 'nutraceuticals', 'Fermentation', 'Ubiquinol', null, null, array['Antioxidant', 'Cellular Energy'], null, null, array[]::text[], null, null),
('wheat-grass-powder', 'Wheat Grass Powder', 'wheat-grass-powder', 'nutraceuticals', 'Triticum aestivum', 'Chlorophyll, Vitamins', null, null, array['Detox', 'Alkalizing', 'Energy'], null, null, array[]::text[], null, null),
('whey-protein-80-90', 'Whey Protein (80% / 90%)', 'whey-protein-80-90', 'nutraceuticals', 'Dairy Source', 'Whey Protein Concentrate/Isolate', null, null, array['Muscle Building', 'Recovery'], null, null, array[]::text[], null, null),
('zeaxanthin-5', 'Zeaxanthin 5%', 'zeaxanthin-5', 'nutraceuticals', 'Tagetes erecta', 'Zeaxanthin', null, null, array['Eye Health', 'Macular Support'], null, null, array[]::text[], null, null)
on conflict (slug) do update set
  name = excluded.name,
  category_id = excluded.category_id,
  botanical_name = excluded.botanical_name,
  active_ingredient = excluded.active_ingredient,
  active_compound = excluded.active_compound,
  concentration = excluded.concentration,
  applications = excluded.applications,
  description = excluded.description,
  image_path = excluded.image_path,
  quality_badges = excluded.quality_badges,
  is_halal = excluded.is_halal,
  popularity = excluded.popularity;

-- Consolidate into final 4-category model
update public.products
set category_id = 'herbal-extracts'
where category_id = 'phytochemicals';

update public.products
set category_id = 'nutraceuticals'
where category_id = 'amino-acids';

delete from public.products
where category_id = 'fruit-juice-powders';

delete from public.product_categories
where id in ('phytochemicals', 'amino-acids', 'fruit-juice-powders');

update public.product_categories
set name = 'Herbal Extracts'
where id = 'herbal-extracts';

update public.product_categories pc
set product_count = coalesce(src.cnt, 0)
from (
  select category_id, count(*)::int as cnt
  from public.products
  group by category_id
) src
where pc.id = src.category_id;

update public.product_categories pc
set product_count = 0
where not exists (
  select 1
  from public.products p
  where p.category_id = pc.id
);

update public.product_categories pc
set example_products = coalesce(src.examples, array[]::text[])
from (
  select
    category_id,
    (array_agg(name order by coalesce(popularity, 0) desc, name asc))[1:3] as examples
  from public.products
  group by category_id
) src
where pc.id = src.category_id;

update public.product_categories pc
set example_products = array[]::text[]
where not exists (
  select 1
  from public.products p
  where p.category_id = pc.id
);

commit;
